### ISSUE TITLE
Upload failed: Facebook error: Failed to create FacebookFile entity. Unable to open resource

### ISSUE THREAD

**Issue by bikrdotnet** [alex-maltsev/TWWOverlay#2]
Getting 
Upload failed: Facebook error: Failed to create FacebookFile entity. Unable to open resource:  (my url) 

When trying to upload the image.  

PHP error log shows: 
[18-Jan-2017 23:47:29 America/Denver] PHP Warning:  fopen(http://followjosh.com/uploads/58806100de328.jpg): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /home8/followjo/public_html/profile/Facebook/FileUpload/FacebookFile.php on line 77

So the file isn't getting cleared from temp for some reason?

**Comment by alex-maltsev** [comment]
There was a bug that I fixed a little more than an hour ago.. Can you make sure that you are using the most up-to-date code?

**Comment by bikrdotnet** [comment]
Might have just found same thing, was it looking for  /uploads instead of ./uploads?  checking your latest push.  Thanks Alex!

**Comment by bikrdotnet** [comment]
That seems to have done it!   Thank you!  Is there any way to force the make profile pic happen instead of just loading that dialog?  It's not too obvious of a CTA on FB's side to make it the profile pic.  Also is the quality of the image dictated on FB's side?  It seemed the root image that gets overlaid comes in rather Lowres but could just be me being tired.

**Comment by alex-maltsev** [comment]
Glad it worked! As far as I can tell there is no way to force it to become the profile picture. It is certainly not the best UX..
There is a constant for the image size in js/profile-pic.js. I set it to 480. It's about the same size that ActionSprout uses. I think some blurring of the overlay happens because JPEG compression doesn't deal well with sharp transitions. (BTW, you should be able to right-click and save image from the main page of the "app").

**Comment by bikrdotnet** [comment]
Thanks so much!!  Now I'm going to convert the index to php so I can pass args in the url and have multiple overlays based on those args.  This is awesome.  thanks again!

**Comment by alex-maltsev** [comment]
You're welcome! I like your idea for multiple overlays.

**Comment by bikrdotnet** [comment]
If it doesn't suck, I'll put in a PR.  :)
